// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/de/webdataplatform/test/sum.proto

package de.webdataplatform.test;

public final class Sum {
  private Sum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SumRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string family = 1;
    /**
     * <code>required string family = 1;</code>
     */
    boolean hasFamily();
    /**
     * <code>required string family = 1;</code>
     */
    java.lang.String getFamily();
    /**
     * <code>required string family = 1;</code>
     */
    com.google.protobuf.ByteString
        getFamilyBytes();

    // required string column = 2;
    /**
     * <code>required string column = 2;</code>
     */
    boolean hasColumn();
    /**
     * <code>required string column = 2;</code>
     */
    java.lang.String getColumn();
    /**
     * <code>required string column = 2;</code>
     */
    com.google.protobuf.ByteString
        getColumnBytes();
  }
  /**
   * Protobuf type {@code SumRequest}
   */
  public static final class SumRequest extends
      com.google.protobuf.GeneratedMessage
      implements SumRequestOrBuilder {
    // Use SumRequest.newBuilder() to construct.
    private SumRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SumRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SumRequest defaultInstance;
    public static SumRequest getDefaultInstance() {
      return defaultInstance;
    }

    public SumRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SumRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              family_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              column_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.webdataplatform.test.Sum.internal_static_SumRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.webdataplatform.test.Sum.internal_static_SumRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.webdataplatform.test.Sum.SumRequest.class, de.webdataplatform.test.Sum.SumRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<SumRequest> PARSER =
        new com.google.protobuf.AbstractParser<SumRequest>() {
      public SumRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SumRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SumRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string family = 1;
    public static final int FAMILY_FIELD_NUMBER = 1;
    private java.lang.Object family_;
    /**
     * <code>required string family = 1;</code>
     */
    public boolean hasFamily() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string family = 1;</code>
     */
    public java.lang.String getFamily() {
      java.lang.Object ref = family_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          family_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string family = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFamilyBytes() {
      java.lang.Object ref = family_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        family_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string column = 2;
    public static final int COLUMN_FIELD_NUMBER = 2;
    private java.lang.Object column_;
    /**
     * <code>required string column = 2;</code>
     */
    public boolean hasColumn() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string column = 2;</code>
     */
    public java.lang.String getColumn() {
      java.lang.Object ref = column_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          column_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string column = 2;</code>
     */
    public com.google.protobuf.ByteString
        getColumnBytes() {
      java.lang.Object ref = column_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        column_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      family_ = "";
      column_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFamily()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasColumn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFamilyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getColumnBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFamilyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getColumnBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.webdataplatform.test.Sum.SumRequest)) {
        return super.equals(obj);
      }
      de.webdataplatform.test.Sum.SumRequest other = (de.webdataplatform.test.Sum.SumRequest) obj;

      boolean result = true;
      result = result && (hasFamily() == other.hasFamily());
      if (hasFamily()) {
        result = result && getFamily()
            .equals(other.getFamily());
      }
      result = result && (hasColumn() == other.hasColumn());
      if (hasColumn()) {
        result = result && getColumn()
            .equals(other.getColumn());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasFamily()) {
        hash = (37 * hash) + FAMILY_FIELD_NUMBER;
        hash = (53 * hash) + getFamily().hashCode();
      }
      if (hasColumn()) {
        hash = (37 * hash) + COLUMN_FIELD_NUMBER;
        hash = (53 * hash) + getColumn().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.webdataplatform.test.Sum.SumRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.webdataplatform.test.Sum.SumRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.webdataplatform.test.Sum.SumRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.webdataplatform.test.Sum.SumRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.webdataplatform.test.Sum.SumRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.webdataplatform.test.Sum.SumRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static de.webdataplatform.test.Sum.SumRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static de.webdataplatform.test.Sum.SumRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static de.webdataplatform.test.Sum.SumRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.webdataplatform.test.Sum.SumRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.webdataplatform.test.Sum.SumRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SumRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements de.webdataplatform.test.Sum.SumRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.webdataplatform.test.Sum.internal_static_SumRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.webdataplatform.test.Sum.internal_static_SumRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.webdataplatform.test.Sum.SumRequest.class, de.webdataplatform.test.Sum.SumRequest.Builder.class);
      }

      // Construct using de.webdataplatform.test.Sum.SumRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        family_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        column_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.webdataplatform.test.Sum.internal_static_SumRequest_descriptor;
      }

      public de.webdataplatform.test.Sum.SumRequest getDefaultInstanceForType() {
        return de.webdataplatform.test.Sum.SumRequest.getDefaultInstance();
      }

      public de.webdataplatform.test.Sum.SumRequest build() {
        de.webdataplatform.test.Sum.SumRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.webdataplatform.test.Sum.SumRequest buildPartial() {
        de.webdataplatform.test.Sum.SumRequest result = new de.webdataplatform.test.Sum.SumRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.family_ = family_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.column_ = column_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.webdataplatform.test.Sum.SumRequest) {
          return mergeFrom((de.webdataplatform.test.Sum.SumRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.webdataplatform.test.Sum.SumRequest other) {
        if (other == de.webdataplatform.test.Sum.SumRequest.getDefaultInstance()) return this;
        if (other.hasFamily()) {
          bitField0_ |= 0x00000001;
          family_ = other.family_;
          onChanged();
        }
        if (other.hasColumn()) {
          bitField0_ |= 0x00000002;
          column_ = other.column_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFamily()) {
          
          return false;
        }
        if (!hasColumn()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.webdataplatform.test.Sum.SumRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.webdataplatform.test.Sum.SumRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string family = 1;
      private java.lang.Object family_ = "";
      /**
       * <code>required string family = 1;</code>
       */
      public boolean hasFamily() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string family = 1;</code>
       */
      public java.lang.String getFamily() {
        java.lang.Object ref = family_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          family_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string family = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFamilyBytes() {
        java.lang.Object ref = family_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          family_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string family = 1;</code>
       */
      public Builder setFamily(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        family_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string family = 1;</code>
       */
      public Builder clearFamily() {
        bitField0_ = (bitField0_ & ~0x00000001);
        family_ = getDefaultInstance().getFamily();
        onChanged();
        return this;
      }
      /**
       * <code>required string family = 1;</code>
       */
      public Builder setFamilyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        family_ = value;
        onChanged();
        return this;
      }

      // required string column = 2;
      private java.lang.Object column_ = "";
      /**
       * <code>required string column = 2;</code>
       */
      public boolean hasColumn() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string column = 2;</code>
       */
      public java.lang.String getColumn() {
        java.lang.Object ref = column_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          column_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string column = 2;</code>
       */
      public com.google.protobuf.ByteString
          getColumnBytes() {
        java.lang.Object ref = column_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          column_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string column = 2;</code>
       */
      public Builder setColumn(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        column_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string column = 2;</code>
       */
      public Builder clearColumn() {
        bitField0_ = (bitField0_ & ~0x00000002);
        column_ = getDefaultInstance().getColumn();
        onChanged();
        return this;
      }
      /**
       * <code>required string column = 2;</code>
       */
      public Builder setColumnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        column_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SumRequest)
    }

    static {
      defaultInstance = new SumRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SumRequest)
  }

  public interface KeyValueOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string key = 1;
    /**
     * <code>required string key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>required string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    // required int64 value = 2 [default = 0];
    /**
     * <code>required int64 value = 2 [default = 0];</code>
     */
    boolean hasValue();
    /**
     * <code>required int64 value = 2 [default = 0];</code>
     */
    long getValue();
  }
  /**
   * Protobuf type {@code KeyValue}
   */
  public static final class KeyValue extends
      com.google.protobuf.GeneratedMessage
      implements KeyValueOrBuilder {
    // Use KeyValue.newBuilder() to construct.
    private KeyValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KeyValue(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KeyValue defaultInstance;
    public static KeyValue getDefaultInstance() {
      return defaultInstance;
    }

    public KeyValue getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KeyValue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              value_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.webdataplatform.test.Sum.internal_static_KeyValue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.webdataplatform.test.Sum.internal_static_KeyValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.webdataplatform.test.Sum.KeyValue.class, de.webdataplatform.test.Sum.KeyValue.Builder.class);
    }

    public static com.google.protobuf.Parser<KeyValue> PARSER =
        new com.google.protobuf.AbstractParser<KeyValue>() {
      public KeyValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KeyValue(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<KeyValue> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    /**
     * <code>required string key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 value = 2 [default = 0];
    public static final int VALUE_FIELD_NUMBER = 2;
    private long value_;
    /**
     * <code>required int64 value = 2 [default = 0];</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 value = 2 [default = 0];</code>
     */
    public long getValue() {
      return value_;
    }

    private void initFields() {
      key_ = "";
      value_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, value_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.webdataplatform.test.Sum.KeyValue)) {
        return super.equals(obj);
      }
      de.webdataplatform.test.Sum.KeyValue other = (de.webdataplatform.test.Sum.KeyValue) obj;

      boolean result = true;
      result = result && (hasKey() == other.hasKey());
      if (hasKey()) {
        result = result && getKey()
            .equals(other.getKey());
      }
      result = result && (hasValue() == other.hasValue());
      if (hasValue()) {
        result = result && (getValue()
            == other.getValue());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasKey()) {
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getValue());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.webdataplatform.test.Sum.KeyValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.webdataplatform.test.Sum.KeyValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.webdataplatform.test.Sum.KeyValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.webdataplatform.test.Sum.KeyValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.webdataplatform.test.Sum.KeyValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.webdataplatform.test.Sum.KeyValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static de.webdataplatform.test.Sum.KeyValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static de.webdataplatform.test.Sum.KeyValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static de.webdataplatform.test.Sum.KeyValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.webdataplatform.test.Sum.KeyValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.webdataplatform.test.Sum.KeyValue prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code KeyValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements de.webdataplatform.test.Sum.KeyValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.webdataplatform.test.Sum.internal_static_KeyValue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.webdataplatform.test.Sum.internal_static_KeyValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.webdataplatform.test.Sum.KeyValue.class, de.webdataplatform.test.Sum.KeyValue.Builder.class);
      }

      // Construct using de.webdataplatform.test.Sum.KeyValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.webdataplatform.test.Sum.internal_static_KeyValue_descriptor;
      }

      public de.webdataplatform.test.Sum.KeyValue getDefaultInstanceForType() {
        return de.webdataplatform.test.Sum.KeyValue.getDefaultInstance();
      }

      public de.webdataplatform.test.Sum.KeyValue build() {
        de.webdataplatform.test.Sum.KeyValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.webdataplatform.test.Sum.KeyValue buildPartial() {
        de.webdataplatform.test.Sum.KeyValue result = new de.webdataplatform.test.Sum.KeyValue(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.webdataplatform.test.Sum.KeyValue) {
          return mergeFrom((de.webdataplatform.test.Sum.KeyValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.webdataplatform.test.Sum.KeyValue other) {
        if (other == de.webdataplatform.test.Sum.KeyValue.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.webdataplatform.test.Sum.KeyValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.webdataplatform.test.Sum.KeyValue) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string key = 1;
      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      // required int64 value = 2 [default = 0];
      private long value_ ;
      /**
       * <code>required int64 value = 2 [default = 0];</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 value = 2 [default = 0];</code>
       */
      public long getValue() {
        return value_;
      }
      /**
       * <code>required int64 value = 2 [default = 0];</code>
       */
      public Builder setValue(long value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 value = 2 [default = 0];</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:KeyValue)
    }

    static {
      defaultInstance = new KeyValue(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:KeyValue)
  }

  public interface SumResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .KeyValue sumMap = 1;
    /**
     * <code>repeated .KeyValue sumMap = 1;</code>
     */
    java.util.List<de.webdataplatform.test.Sum.KeyValue> 
        getSumMapList();
    /**
     * <code>repeated .KeyValue sumMap = 1;</code>
     */
    de.webdataplatform.test.Sum.KeyValue getSumMap(int index);
    /**
     * <code>repeated .KeyValue sumMap = 1;</code>
     */
    int getSumMapCount();
    /**
     * <code>repeated .KeyValue sumMap = 1;</code>
     */
    java.util.List<? extends de.webdataplatform.test.Sum.KeyValueOrBuilder> 
        getSumMapOrBuilderList();
    /**
     * <code>repeated .KeyValue sumMap = 1;</code>
     */
    de.webdataplatform.test.Sum.KeyValueOrBuilder getSumMapOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code SumResponse}
   */
  public static final class SumResponse extends
      com.google.protobuf.GeneratedMessage
      implements SumResponseOrBuilder {
    // Use SumResponse.newBuilder() to construct.
    private SumResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SumResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SumResponse defaultInstance;
    public static SumResponse getDefaultInstance() {
      return defaultInstance;
    }

    public SumResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SumResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                sumMap_ = new java.util.ArrayList<de.webdataplatform.test.Sum.KeyValue>();
                mutable_bitField0_ |= 0x00000001;
              }
              sumMap_.add(input.readMessage(de.webdataplatform.test.Sum.KeyValue.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          sumMap_ = java.util.Collections.unmodifiableList(sumMap_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.webdataplatform.test.Sum.internal_static_SumResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.webdataplatform.test.Sum.internal_static_SumResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.webdataplatform.test.Sum.SumResponse.class, de.webdataplatform.test.Sum.SumResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<SumResponse> PARSER =
        new com.google.protobuf.AbstractParser<SumResponse>() {
      public SumResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SumResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SumResponse> getParserForType() {
      return PARSER;
    }

    // repeated .KeyValue sumMap = 1;
    public static final int SUMMAP_FIELD_NUMBER = 1;
    private java.util.List<de.webdataplatform.test.Sum.KeyValue> sumMap_;
    /**
     * <code>repeated .KeyValue sumMap = 1;</code>
     */
    public java.util.List<de.webdataplatform.test.Sum.KeyValue> getSumMapList() {
      return sumMap_;
    }
    /**
     * <code>repeated .KeyValue sumMap = 1;</code>
     */
    public java.util.List<? extends de.webdataplatform.test.Sum.KeyValueOrBuilder> 
        getSumMapOrBuilderList() {
      return sumMap_;
    }
    /**
     * <code>repeated .KeyValue sumMap = 1;</code>
     */
    public int getSumMapCount() {
      return sumMap_.size();
    }
    /**
     * <code>repeated .KeyValue sumMap = 1;</code>
     */
    public de.webdataplatform.test.Sum.KeyValue getSumMap(int index) {
      return sumMap_.get(index);
    }
    /**
     * <code>repeated .KeyValue sumMap = 1;</code>
     */
    public de.webdataplatform.test.Sum.KeyValueOrBuilder getSumMapOrBuilder(
        int index) {
      return sumMap_.get(index);
    }

    private void initFields() {
      sumMap_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getSumMapCount(); i++) {
        if (!getSumMap(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < sumMap_.size(); i++) {
        output.writeMessage(1, sumMap_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < sumMap_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sumMap_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.webdataplatform.test.Sum.SumResponse)) {
        return super.equals(obj);
      }
      de.webdataplatform.test.Sum.SumResponse other = (de.webdataplatform.test.Sum.SumResponse) obj;

      boolean result = true;
      result = result && getSumMapList()
          .equals(other.getSumMapList());
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getSumMapCount() > 0) {
        hash = (37 * hash) + SUMMAP_FIELD_NUMBER;
        hash = (53 * hash) + getSumMapList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.webdataplatform.test.Sum.SumResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.webdataplatform.test.Sum.SumResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.webdataplatform.test.Sum.SumResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.webdataplatform.test.Sum.SumResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.webdataplatform.test.Sum.SumResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.webdataplatform.test.Sum.SumResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static de.webdataplatform.test.Sum.SumResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static de.webdataplatform.test.Sum.SumResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static de.webdataplatform.test.Sum.SumResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.webdataplatform.test.Sum.SumResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.webdataplatform.test.Sum.SumResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SumResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements de.webdataplatform.test.Sum.SumResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.webdataplatform.test.Sum.internal_static_SumResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.webdataplatform.test.Sum.internal_static_SumResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.webdataplatform.test.Sum.SumResponse.class, de.webdataplatform.test.Sum.SumResponse.Builder.class);
      }

      // Construct using de.webdataplatform.test.Sum.SumResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSumMapFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (sumMapBuilder_ == null) {
          sumMap_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          sumMapBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.webdataplatform.test.Sum.internal_static_SumResponse_descriptor;
      }

      public de.webdataplatform.test.Sum.SumResponse getDefaultInstanceForType() {
        return de.webdataplatform.test.Sum.SumResponse.getDefaultInstance();
      }

      public de.webdataplatform.test.Sum.SumResponse build() {
        de.webdataplatform.test.Sum.SumResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.webdataplatform.test.Sum.SumResponse buildPartial() {
        de.webdataplatform.test.Sum.SumResponse result = new de.webdataplatform.test.Sum.SumResponse(this);
        int from_bitField0_ = bitField0_;
        if (sumMapBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            sumMap_ = java.util.Collections.unmodifiableList(sumMap_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.sumMap_ = sumMap_;
        } else {
          result.sumMap_ = sumMapBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.webdataplatform.test.Sum.SumResponse) {
          return mergeFrom((de.webdataplatform.test.Sum.SumResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.webdataplatform.test.Sum.SumResponse other) {
        if (other == de.webdataplatform.test.Sum.SumResponse.getDefaultInstance()) return this;
        if (sumMapBuilder_ == null) {
          if (!other.sumMap_.isEmpty()) {
            if (sumMap_.isEmpty()) {
              sumMap_ = other.sumMap_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSumMapIsMutable();
              sumMap_.addAll(other.sumMap_);
            }
            onChanged();
          }
        } else {
          if (!other.sumMap_.isEmpty()) {
            if (sumMapBuilder_.isEmpty()) {
              sumMapBuilder_.dispose();
              sumMapBuilder_ = null;
              sumMap_ = other.sumMap_;
              bitField0_ = (bitField0_ & ~0x00000001);
              sumMapBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSumMapFieldBuilder() : null;
            } else {
              sumMapBuilder_.addAllMessages(other.sumMap_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getSumMapCount(); i++) {
          if (!getSumMap(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.webdataplatform.test.Sum.SumResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.webdataplatform.test.Sum.SumResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .KeyValue sumMap = 1;
      private java.util.List<de.webdataplatform.test.Sum.KeyValue> sumMap_ =
        java.util.Collections.emptyList();
      private void ensureSumMapIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          sumMap_ = new java.util.ArrayList<de.webdataplatform.test.Sum.KeyValue>(sumMap_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          de.webdataplatform.test.Sum.KeyValue, de.webdataplatform.test.Sum.KeyValue.Builder, de.webdataplatform.test.Sum.KeyValueOrBuilder> sumMapBuilder_;

      /**
       * <code>repeated .KeyValue sumMap = 1;</code>
       */
      public java.util.List<de.webdataplatform.test.Sum.KeyValue> getSumMapList() {
        if (sumMapBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sumMap_);
        } else {
          return sumMapBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .KeyValue sumMap = 1;</code>
       */
      public int getSumMapCount() {
        if (sumMapBuilder_ == null) {
          return sumMap_.size();
        } else {
          return sumMapBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .KeyValue sumMap = 1;</code>
       */
      public de.webdataplatform.test.Sum.KeyValue getSumMap(int index) {
        if (sumMapBuilder_ == null) {
          return sumMap_.get(index);
        } else {
          return sumMapBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .KeyValue sumMap = 1;</code>
       */
      public Builder setSumMap(
          int index, de.webdataplatform.test.Sum.KeyValue value) {
        if (sumMapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSumMapIsMutable();
          sumMap_.set(index, value);
          onChanged();
        } else {
          sumMapBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .KeyValue sumMap = 1;</code>
       */
      public Builder setSumMap(
          int index, de.webdataplatform.test.Sum.KeyValue.Builder builderForValue) {
        if (sumMapBuilder_ == null) {
          ensureSumMapIsMutable();
          sumMap_.set(index, builderForValue.build());
          onChanged();
        } else {
          sumMapBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .KeyValue sumMap = 1;</code>
       */
      public Builder addSumMap(de.webdataplatform.test.Sum.KeyValue value) {
        if (sumMapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSumMapIsMutable();
          sumMap_.add(value);
          onChanged();
        } else {
          sumMapBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .KeyValue sumMap = 1;</code>
       */
      public Builder addSumMap(
          int index, de.webdataplatform.test.Sum.KeyValue value) {
        if (sumMapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSumMapIsMutable();
          sumMap_.add(index, value);
          onChanged();
        } else {
          sumMapBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .KeyValue sumMap = 1;</code>
       */
      public Builder addSumMap(
          de.webdataplatform.test.Sum.KeyValue.Builder builderForValue) {
        if (sumMapBuilder_ == null) {
          ensureSumMapIsMutable();
          sumMap_.add(builderForValue.build());
          onChanged();
        } else {
          sumMapBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .KeyValue sumMap = 1;</code>
       */
      public Builder addSumMap(
          int index, de.webdataplatform.test.Sum.KeyValue.Builder builderForValue) {
        if (sumMapBuilder_ == null) {
          ensureSumMapIsMutable();
          sumMap_.add(index, builderForValue.build());
          onChanged();
        } else {
          sumMapBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .KeyValue sumMap = 1;</code>
       */
      public Builder addAllSumMap(
          java.lang.Iterable<? extends de.webdataplatform.test.Sum.KeyValue> values) {
        if (sumMapBuilder_ == null) {
          ensureSumMapIsMutable();
          super.addAll(values, sumMap_);
          onChanged();
        } else {
          sumMapBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .KeyValue sumMap = 1;</code>
       */
      public Builder clearSumMap() {
        if (sumMapBuilder_ == null) {
          sumMap_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          sumMapBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .KeyValue sumMap = 1;</code>
       */
      public Builder removeSumMap(int index) {
        if (sumMapBuilder_ == null) {
          ensureSumMapIsMutable();
          sumMap_.remove(index);
          onChanged();
        } else {
          sumMapBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .KeyValue sumMap = 1;</code>
       */
      public de.webdataplatform.test.Sum.KeyValue.Builder getSumMapBuilder(
          int index) {
        return getSumMapFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .KeyValue sumMap = 1;</code>
       */
      public de.webdataplatform.test.Sum.KeyValueOrBuilder getSumMapOrBuilder(
          int index) {
        if (sumMapBuilder_ == null) {
          return sumMap_.get(index);  } else {
          return sumMapBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .KeyValue sumMap = 1;</code>
       */
      public java.util.List<? extends de.webdataplatform.test.Sum.KeyValueOrBuilder> 
           getSumMapOrBuilderList() {
        if (sumMapBuilder_ != null) {
          return sumMapBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sumMap_);
        }
      }
      /**
       * <code>repeated .KeyValue sumMap = 1;</code>
       */
      public de.webdataplatform.test.Sum.KeyValue.Builder addSumMapBuilder() {
        return getSumMapFieldBuilder().addBuilder(
            de.webdataplatform.test.Sum.KeyValue.getDefaultInstance());
      }
      /**
       * <code>repeated .KeyValue sumMap = 1;</code>
       */
      public de.webdataplatform.test.Sum.KeyValue.Builder addSumMapBuilder(
          int index) {
        return getSumMapFieldBuilder().addBuilder(
            index, de.webdataplatform.test.Sum.KeyValue.getDefaultInstance());
      }
      /**
       * <code>repeated .KeyValue sumMap = 1;</code>
       */
      public java.util.List<de.webdataplatform.test.Sum.KeyValue.Builder> 
           getSumMapBuilderList() {
        return getSumMapFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          de.webdataplatform.test.Sum.KeyValue, de.webdataplatform.test.Sum.KeyValue.Builder, de.webdataplatform.test.Sum.KeyValueOrBuilder> 
          getSumMapFieldBuilder() {
        if (sumMapBuilder_ == null) {
          sumMapBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              de.webdataplatform.test.Sum.KeyValue, de.webdataplatform.test.Sum.KeyValue.Builder, de.webdataplatform.test.Sum.KeyValueOrBuilder>(
                  sumMap_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          sumMap_ = null;
        }
        return sumMapBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:SumResponse)
    }

    static {
      defaultInstance = new SumResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SumResponse)
  }

  /**
   * Protobuf service {@code SumService}
   */
  public static abstract class SumService
      implements com.google.protobuf.Service {
    protected SumService() {}

    public interface Interface {
      /**
       * <code>rpc getSum(.SumRequest) returns (.SumResponse);</code>
       */
      public abstract void getSum(
          com.google.protobuf.RpcController controller,
          de.webdataplatform.test.Sum.SumRequest request,
          com.google.protobuf.RpcCallback<de.webdataplatform.test.Sum.SumResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new SumService() {
        @java.lang.Override
        public  void getSum(
            com.google.protobuf.RpcController controller,
            de.webdataplatform.test.Sum.SumRequest request,
            com.google.protobuf.RpcCallback<de.webdataplatform.test.Sum.SumResponse> done) {
          impl.getSum(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getSum(controller, (de.webdataplatform.test.Sum.SumRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return de.webdataplatform.test.Sum.SumRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return de.webdataplatform.test.Sum.SumResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getSum(.SumRequest) returns (.SumResponse);</code>
     */
    public abstract void getSum(
        com.google.protobuf.RpcController controller,
        de.webdataplatform.test.Sum.SumRequest request,
        com.google.protobuf.RpcCallback<de.webdataplatform.test.Sum.SumResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return de.webdataplatform.test.Sum.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getSum(controller, (de.webdataplatform.test.Sum.SumRequest)request,
            com.google.protobuf.RpcUtil.<de.webdataplatform.test.Sum.SumResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return de.webdataplatform.test.Sum.SumRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return de.webdataplatform.test.Sum.SumResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends de.webdataplatform.test.Sum.SumService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getSum(
          com.google.protobuf.RpcController controller,
          de.webdataplatform.test.Sum.SumRequest request,
          com.google.protobuf.RpcCallback<de.webdataplatform.test.Sum.SumResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          de.webdataplatform.test.Sum.SumResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            de.webdataplatform.test.Sum.SumResponse.class,
            de.webdataplatform.test.Sum.SumResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public de.webdataplatform.test.Sum.SumResponse getSum(
          com.google.protobuf.RpcController controller,
          de.webdataplatform.test.Sum.SumRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public de.webdataplatform.test.Sum.SumResponse getSum(
          com.google.protobuf.RpcController controller,
          de.webdataplatform.test.Sum.SumRequest request)
          throws com.google.protobuf.ServiceException {
        return (de.webdataplatform.test.Sum.SumResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          de.webdataplatform.test.Sum.SumResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:SumService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SumRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SumRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_KeyValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_KeyValue_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SumResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SumResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%src/de/webdataplatform/test/sum.proto\"" +
      ",\n\nSumRequest\022\016\n\006family\030\001 \002(\t\022\016\n\006column\030" +
      "\002 \002(\t\")\n\010KeyValue\022\013\n\003key\030\001 \002(\t\022\020\n\005value\030" +
      "\002 \002(\003:\0010\"(\n\013SumResponse\022\031\n\006sumMap\030\001 \003(\0132" +
      "\t.KeyValue21\n\nSumService\022#\n\006getSum\022\013.Sum" +
      "Request\032\014.SumResponseB&\n\027de.webdataplatf" +
      "orm.testB\003SumH\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SumRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SumRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SumRequest_descriptor,
              new java.lang.String[] { "Family", "Column", });
          internal_static_KeyValue_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_KeyValue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_KeyValue_descriptor,
              new java.lang.String[] { "Key", "Value", });
          internal_static_SumResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_SumResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SumResponse_descriptor,
              new java.lang.String[] { "SumMap", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
